modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dwbscpsad"
version="1.0.0"
displayName="Dweebscape Skyblock Append Disk (SAD)"
displayURL="https://twitch.tv/MyrajusEleen"
credits="Utilized MCreator for most parts of this project."
authors="EleenTyasi"
description="Append Disk Installed. Hello there! This is an Append Disk for Skyblock. Please ensure you have this mod  along side of a world generator that  generates a skyblock or void island! Thanks!"

[[dependencies.dwbscpsad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




